---
all:
  children:
    kafka:
      hosts:

        kafka-01:
          ansible_host: 10.148.0.3
          ansible_user: rhel9
          kafka_node_id: 1
          kafka_host: 10.148.0.3

        kafka-02:
          ansible_host: 10.148.0.2
          ansible_user: rhel9
          kafka_node_id: 2
          kafka_host: 10.148.0.2
